services:
  react-app:
    build: .
    ports:
      - "3000:80"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-app.rule=Host(`davidfdzmorilla.dev`)"
      - "traefik.http.routers.react-app.entrypoints=websecure"
      - "traefik.http.routers.react-app.tls.certresolver=myresolver"
    volumes:
      - .:/app
      - /app/node_modules

networks:
  traefik_proxy:
    external: true

