services:
  portfolio-app:
    image: davidfdzmorilla/portfolio-app:latest
    ports:
      - "3000:80"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-app.rule=Host(`davidfdzmorilla.dev`)"
      - "traefik.http.routers.portfolio-app.entrypoints=websecure"
      - "traefik.http.routers.portfolio-app.tls.certresolver=myresolver"

networks:
  traefik_proxy:
    external: true
