name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      # 2. Construir la imagen Docker
      - name: Construir la imagen de Docker
        run: |
          docker build -t portfolio-app .

      # 3. Desplegar en el servidor
      - name: Desplegar en el servidor
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop portfolio-app || true
            docker rm portfolio-app || true
            docker pull tu-repo/portfolio-app:latest
            docker run -d -p 80:80 --name portfolio-app tu-repo/portfolio-app:latest

      # 4. Limpiar imágenes locales
      - name: Limpiar imágenes locales
        run: |
          docker system prune -af
