name: Deploy React App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      # 2. Loguearse en Docker Hub
      - name: Loguearse en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Construir la imagen Docker
      - name: Construir la imagen de Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-app:latest .

      # 4. Empujar la imagen a Docker Hub
      - name: Empujar la imagen a Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-app:latest

      # 5. Desplegar en el servidor usando Docker Compose
      - name: Desplegar en el servidor
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/david/compose/portfolio
            docker-compose pull
            docker-compose up -d --build
